### ISSUE TITLE
The time of runing forward 

### ISSUE THREAD

**Issue by Trepassing** [Xtra-Computing/thundergbm#16]
10 images(250*250)takes me 17s to train a model.
But it takes me 0.6s to predict by my trained model.
Is it normal that I spent so long time to run forward?
thanks!!!

**Comment by zeyiwen** [comment]
This is problem dependent... 

It seems your question is irrelevant to ThunderGBM? If so, you may post questions like this in other forums (e.g., StackOverflow). Let's keep here for ThunderGBM related issues :)
