### ISSUE TITLE
How to solve Error LNK2019 unresolved external symbol _main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)

### ISSUE THREAD

**Issue by oChristineo** [Xtra-Computing/thundergbm#24]

**Comment by zeyiwen** [comment]
It would be good if you can open the issue in English. We are trying to help. But, would you please read these [10 golden rules of asking questions in the OpenSource community](http://blog.vogella.com/2010/03/09/asking-community-questions/) first?

**Comment by oChristineo** [comment]
I cloned the project. I executed cmake .. -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE -G "Visual Studio 15 2017 Win64", and opened the thundergbm. sln file it generated in vs2017 for Windows10|CUDA 10.1, and the error occurred halfway through the compilation.

**Comment by oChristineo** [comment]
> It would be good if you can open the issue in English. We are trying to help. But, would you please read these [10 golden rules of asking questions in the OpenSource community](http://blog.vogella.com/2010/03/09/asking-community-questions/) first?

Thanks for your suggestion! This issue has been resolved.

**Comment by oChristineo** [comment]
This issue has been resolved.
