### ISSUE TITLE
No TGBMClassifier and TGBMRegressor in Windows version of thundergbm_scikit.py

### ISSUE THREAD

**Issue by canasta** [Xtra-Computing/thundergbm#27]
I installed thundergbm via `pip install thundergbm-cu10-0.2.0-py3-none-win_amd64.whl` which is described in quick install of README.rd.
There are no TGBMClassifier and TGBMRegressor in thundergbm_scikit.py, but only TGBMModel.
I think you'd better to make these two classes in thundergbm_scikit.py or rewrite how-to-use.

**Comment by Kurt-Liuhf** [comment]
Thanks for the comments. We have updated the '.whl' file now. You can reinstall thundergbm via `pip install thundergbm-0.3.4-py3-win64.whl`, which is described in quick install of  README.rd. Also, I suggest that you should read the documentation of [how-to.md](https://github.com/Xtra-Computing/thundergbm/blob/master/docs/how-to.md), which would help you understand how to build your own `.whl` file.

**Comment by canasta** [comment]
Thanks for updating. But I think the name new file is wrong.
I'm not familiar about wheel files, so I don't know exactly whether it is wrong or not, but according to [PEP 491](https://www.python.org/dev/peps/pep-0491/#file-name-convention), The wheel filename must be like `{distribution}-{version}(-{build tag})?-{python tag}-{abi tag}-{platform tag}.whl`. So the name of uploaded wheel file has to be changed like `thundergbm-0.3.4-py3-none-win_amd64.whl`.
