### ISSUE TITLE
CUDA version

### ISSUE THREAD

**Issue by canasta** [Xtra-Computing/thundergbm#28]
I installed thudergbm with wheel file `thundergbm-0.3.4-py3-win64.whl`. And there is an problem in thundergbm.dll. It finds `cusparse64_10.dll`, but there is only `cusparse64_100.dll` in CUDA 10.0. So it cause WinError 126. When I search `cusparse64_10.dll` on Google, it exists in 10.1 only. If you using CUDA 10.1, then I recommend to build file again or to fix README.

**Comment by zeyiwen** [comment]
Thanks. We will fix the readme file.

**Comment by Kurt-Liuhf** [comment]
Thanks for reminding me.  I have rebuilt the `.whl` file by using CUDA 10.0.1. You can download the newest file and install it through `pip` now. Also, I have renamed the `.whl` file according to [PEP 491](https://www.python.org/dev/peps/pep-0491/#file-name-convention) in README.md.
