### ISSUE TITLE
Jupyter Notebook Kernel died after TGBMRegressor().fit(X_train, y_train)

### ISSUE THREAD

**Issue by ArtyomSalnikov** [Xtra-Computing/thundergbm#29]
`import json`
`import numpy as np`
`import pandas as pd`
`import thundergbm`

`INPUT_DIR = 'https://raw.githubusercontent.com/ArtyomSalnikov/tmp/master/'`
`X_train = pd.read_csv(INPUT_DIR+'X_train.csv')`
`y_train = np.ravel(pd.read_json(INPUT_DIR+'y_train.json').values)`
`thundergbm.TGBMRegressor().fit(X_train, y_train)`

**Comment by Kurt-Liuhf** [comment]
Hi @ArtyomSalnikov , thanks for your feedback. We have fixed the bugs and you can now reinstall `thundergbm` via `pip`.
