### ISSUE TITLE
Request: Run quietly (surpress all prints) with sci-kit interface

### ISSUE THREAD

**Issue by beevabeeva** [Xtra-Computing/thundergbm#31]
Hi,
I am implementing ThunderGBM in an AutoML framework with the goal to optimise for speed.
It would be great if we had the option to run ` .fit()` and ` .predict()` methods with no printing to stdout.

I tried searching in the Python files but it became apparent that it is not there.
I did see the a reply in another issue that this is currently not possible.
If you tell me where/how to do this, I could give it a try. 

Thanks

**Comment by zeyiwen** [comment]
Did you try the ``verbose`` option descript in the [documentation](https://github.com/Xtra-Computing/thundergbm/blob/master/docs/parameters.md)?

**Comment by Tripton** [comment]
The verbose parameter only suppresses logs of type "Debug" and "Trace" I think.
Maybe you could change it in the code "scikit_tgbm.cpp" in line 42, but I didn't test it.

My solution was following:
`import os`
`# On Unix or Darwin`
`devnull` = open("/dev/null", `'w')`
`# On Windows`
`devnull = open("NUL" 'w')` 
`os.dup2(devnull.fileno(), 1)`

`tgbm.predict(x) #Replace this line with your fit or predict function.`

`os.dup2(oldstdout_fno, 1)`

**Comment by zeyiwen** [comment]
Thanks @Tripton. Changing the logger is the right way to go if you want to disable 'all' the outputs. We'll disable the ``Info`` level output for the ``verbose`` option.

**Comment by beevabeeva** [comment]
Thank you everyone!
