### ISSUE TITLE
Bug: Memory Leak in sci-kit interface

### ISSUE THREAD

**Issue by Tripton** [Xtra-Computing/thundergbm#32]
Hello,

I'm running TGBM on a Windows 10 machine with Cuda 10.
In my use case I create a lot of different GBDTs, which go out of scope after some time.
The problem is, that the gpu memory stays allocated.

My expectation were, that when pythons garbage collector deletes the instance, the memory gets freed. However, even when I explicitly delete the instance, the memory stays allocated.

I think to resolve this Issue in "scikit_tgbm.cpp" the model_free function must be extended to free the allocated memory. Currently, I don't know how to do this. But maybe if I find time I will take a deeper look in memory management with Cuda.

I found a very very ugly workaround by changing some code in the "thundergbm.py".
I extended the __del__ function of TGBMModel to reload the whole dll. This isn't a good solution but okayish as a workaround if really required by somebody.

**Comment by zeyiwen** [comment]
Thanks for the feedback! We will look into the problem and get back to you. I hope we could reproduce the problem. Meanwhile, would you please share your solution with us? It may be helpful for bug tracking and reproduction. Pasting the code in this issue would be okay.

**Comment by Tripton** [comment]
Thank you for your quick reply!

This is a minimal example which leads to an OOM Cuda Error. You can verify the memory leak by observing "nvidia-smi" tool.

```python
from thundergbm import TGBMRegressor
from sklearn.datasets import load_boston
from sklearn.metrics import mean_squared_error
from math import sqrt
import numpy as np



def main():
    rmse_sum = 0
    iterations = 100
    x, y = load_boston(return_X_y=True)

    num_repeat = 10000
    x = np.repeat(x, num_repeat, axis=0)
    y = np.repeat(y, num_repeat)

    for _ in range(iterations):
        clf = TGBMRegressor()
        clf.fit(x, y)
        y_pred = clf.predict(x)
        rmse = sqrt(mean_squared_error(y, y_pred))
        rmse_sum += rmse
        # This should happen with python gc automaticly, but still dosn't solve the problem
        del clf
    print(rmse_sum/iterations)

if __name__ == '__main__':
    main()
```

My workaround involves modifications in the "thundergbm.py".
At the begin of the script you are setting the "lib_path" variable (around line 26).
Between "lib_path" and "OBJECTIVE_TYPE" insert following Code and replace the old one in betwenn:
```python
def load_tgbm():
	global thundergbm
	global libHandel
	if path.exists(lib_path):
		thundergbm = CDLL(lib_path)
		libHandel = thundergbm._handle
	else:
		raise RuntimeError("Please build the library first!")
load_tgbm()
		
def reload_tgbm():
	global thundergbm
	del thundergbm
	windll.kernel32.FreeLibrary.argtypes = [wintypes.HMODULE]
	windll.kernel32.FreeLibrary(libHandel)
	load_tgbm()
```

After that, add to the "__del__" method of the TGBMModel Class a "reload_tgbm()". So it should look likes this:
```python
def __del__(self):
    if self.model is not None:
        thundergbm.model_free(byref(self.model))
```

Note: This should only work on Windows, cause it depends on windll.kernel32.FreeLibrary. For Unix I think ctypes,FreeLibrary should work.

**Comment by Tripton** [comment]
Yep exactly. It's just an ugly workaround, so I can use TGBM in my application but it's creating a huge overhead. Would be nice if you are able to free the memory in the correct way. If I can help you in any way just tell me.

**Comment by Kurt-Liuhf** [comment]
Hi @Tripton, we think we have fixed the memory leaking problem. We ran some test on our server and no more memory leaking found. You should reinstall ThunderGBM through `pip` and have a try. And feel free to share with us if you find any problems.

**Comment by Tripton** [comment]
Hi @Kurt-Liuhf, thank you very much! It looks like the problem is solved!:) But is it possible, that you require a bit more GPU Ram then before? If so I think it was introduced in [this ](https://github.com/Xtra-Computing/thundergbm/commit/98f235d8cecf9bd56a47d0e0a849f06597084bc8) commit. Thank you very much for your effort!

I have also some other issues/questions. Is there any way to contact you, or should I open a new issue?

**Comment by zeyiwen** [comment]
Sounds cool. The [commit](https://github.com/Xtra-Computing/thundergbm/commit/98f235d8cecf9bd56a47d0e0a849f06597084bc8) doesn't require extra GPU memory. My guess is the memory monitor you used may be not so accurate? Anyway, we like to close this issue, as the bug is now fixed.
