### ISSUE TITLE
ThunderGBM in Google Colab?

### ISSUE THREAD

**Issue by vprelovac** [Xtra-Computing/thundergbm#38]
Lookin for a  way to run this in Google Colab environment, thanks.

**Comment by Kurt-Liuhf** [comment]
Hi @vprelovac ,  can you install ThunderGBM in Google Colab through command `!pip install thundergbm`? We have not tried running our library in Colab yet, but we encourage you to have a try and give us some feedback! Thank you!

**Comment by vprelovac** [comment]
Yes, and it doesn't work. Colab had huge community of ML users and I suggest that you include it as part of testing.

**Comment by kirimaru-jp** [comment]
@Kurt-Liuhf 
It works for me, with the following example, adapted from [sklearn](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html)

```
from thundergbm import TGBMClassifier
clf = TGBMClassifier(depth=2)
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=1000, n_features=4,
                           n_informative=2, n_redundant=0,
                           random_state=0, shuffle=False)
clf.fit(X, y)

z = clf.predict(X[:20,]**2)
z
```
Results:
```
array([0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])
```
