### ISSUE TITLE
-bash: ./bin/thundergbm-train: file not found

### ISSUE THREAD

**Issue by ShaoQiBNU** [Xtra-Computing/thundergbm#5]
I input the commend ./bin/thundergbm-train ../dataset/machine.conf, but get the result:
-bash: ./bin/thundergbm-train: 没有那个文件或目录

**Comment by zeyiwen** [comment]
* make sure you have built the executable.
* make sure you run the command under the root directory of ThunderGBM.

**Comment by ShaoQiBNU** [comment]
Thank you! 
My cmake version is 2.8, so the commend mkdir build && cd build && cmake .. && make -j didn't take effect.

**Comment by zeyiwen** [comment]
Is there any error message when you are building the code? Please show us the output and then we can help identify what problem is.
