### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by mahi045** [Xtra-Computing/thundergbm#51]
I am getting this error after executing `make -j`:
```
/thundergbm/src/thundergbm/hist_cut.cu(142): error: a reference of type "SyncArray<float> &" (not const-qualified) cannot be initialized with a value of type "SyncArray<float_type>"
```
I am using the code of the **support_cuda11** branch (as my CUDA version is 11).

**Comment by Kurt-Liuhf** [comment]
Hi @mahi045, thanks for the feedback. The issue is fixed. Please pull the updated repository and have a try.
Thanks.

**Comment by mahi045** [comment]
Hi @Kurt-Liuhf,
First of all, thanks for your response and immediate action.
I pull the branch and then tried. Still, I cannot compile. I am getting the same error.

**Comment by Kurt-Liuhf** [comment]
Thanks. I have tested this branch on two computers but no error showed. Can you delete the library and clone it from GitHub again?

**Comment by mahi045** [comment]
Yes, successfully compiled it. 
Thanks for your immediate action.

**Comment by Kurt-Liuhf** [comment]
Issues have been fixed. So, I would like to close it.
Thanks.
