### ISSUE TITLE
Makefile:83: recipe for target 'all' failed

### ISSUE THREAD

**Issue by DreamitDoItFrom0** [Xtra-Computing/thundergbm#6]
src/thundergbm/CMakeFiles/thundergbm.dir/build.make:147: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_tree.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_tree.cu.o] Error 1
In file included from /media/pci/4T/ymj/workspace/xinyong_zhineng/thundergbm/include/thundergbm/syncarray.h:9:0,
                 from /media/pci/4T/ymj/workspace/xinyong_zhineng/thundergbm/include/thundergbm/tree.h:11,
                 from /media/pci/4T/ymj/workspace/xinyong_zhineng/thundergbm/src/thundergbm/trainer.cu:8:
/media/pci/4T/ymj/workspace/xinyong_zhineng/thundergbm/include/thundergbm/syncmem.h:9:34: fatal error: cub/util_allocator.cuh: 没有那个文件或目录
compilation terminated.
CMake Error at thundergbm_generated_trainer.cu.o.cmake:207 (message):
  Error generating
  /media/pci/4T/ymj/workspace/xinyong_zhineng/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir//./thundergbm_generated_trainer.cu.o

src/thundergbm/CMakeFiles/thundergbm.dir/build.make:126: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_trainer.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_trainer.cu.o] Error 1
CMakeFiles/Makefile2:126: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/all' failed
make[1]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I have download the  latest version of ThunderGBM, but it still can't make it.
can you tell me how to fix it? Thank you very much!

**Comment by zeyiwen** [comment]
Did you clone ```cub```? It seems there are some files in ```cub``` missing. Please make sure you execute the following command (cf. instructions on installation).
```#under the directory of thundergbm
git submodule init cub && git submodule update
```

**Comment by DreamitDoItFrom0** [comment]
> Did you clone `cub`? It seems there are some files in `cub` missing. Please make sure you execute the following command (cf. instructions on installation).
> 
> ```
> git submodule init cub && git submodule update
> ```

Thank you ,I have cloned  the cub just now,but I have another problem ,you can see it 

src/thundergbm/CMakeFiles/thundergbm.dir/build.make:147: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_tree.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_tree.cu.o] Error 1
96 errors detected in the compilation of "/tmp/tmpxft_00004d14_00000000-7_tree_builder.cpp1.ii".
CMake Error at thundergbm_generated_tree_builder.cu.o.cmake:266 (message):
  Error generating file
  /media/pci/4T/ymj/workspace/xinyong_zhineng/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir/builder/./thundergbm_generated_tree_builder.cu.o


src/thundergbm/CMakeFiles/thundergbm.dir/build.make:63: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/builder/thundergbm_generated_tree_builder.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/builder/thundergbm_generated_tree_builder.cu.o] Error 1
94 errors detected in the compilation of "/tmp/tmpxft_00004d36_00000000-7_hist_cut.cpp1.ii".
CMake Error at thundergbm_generated_hist_cut.cu.o.cmake:266 (message):
  Error generating file
  /media/pci/4T/ymj/workspace/xinyong_zhineng/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir//./thundergbm_generated_hist_cut.cu.o


src/thundergbm/CMakeFiles/thundergbm.dir/build.make:161: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_hist_cut.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_hist_cut.cu.o] Error 1
92 errors detected in the compilation of "/tmp/tmpxft_00004d73_00000000-7_trainer.cpp1.ii".
CMake Error at thundergbm_generated_trainer.cu.o.cmake:266 (message):
  Error generating file
  /media/pci/4T/ymj/workspace/xinyong_zhineng/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir//./thundergbm_generated_trainer.cu.o


src/thundergbm/CMakeFiles/thundergbm.dir/build.make:126: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_trainer.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_trainer.cu.o] Error 1
CMakeFiles/Makefile2:126: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/all' failed
make[1]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zeyiwen** [comment]
Please remove the ```build``` folder and repeat the instructions for building the code.

**Comment by DreamitDoItFrom0** [comment]
> Please remove the `build` folder and repeat the instructions for building the code.

I do that as you say, but it still has the same problem.

92 errors detected in the compilation of "/tmp/tmpxft_000066e6_00000000-7_objective_function.cpp1.ii".
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11140): error: argument of type "void *" is incompatible with parameter of type "double *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(55): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11149): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(63): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(73): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11160): error: argument of type "void *" is incompatible with parameter of type "int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(81): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512pfintrin.h(91): error: argument of type "void *" is incompatible with parameter of type "const long long *"

**Comment by shijianjian** [comment]
@zeyiwen Hi, I got problem with boost.
I use boost 1.69.0 and cmake 3.13.3

```
/usr/local/lib/boost/include/boost/core/noncopyable.hpp(42): error: defaulted default constructor cannot be constexpr because the corresponding implicitly declared default constructor would not be constexpr

/usr/local/lib/boost/include/boost/mpl/print.hpp(64): warning: integer conversion resulted in a change of sign

1 error detected in the compilation of "/tmp/tmpxft_0000135d_00000000-6_trainer.cpp1.ii".
CMake Error at thundergbm_generated_trainer.cu.o.Release.cmake:279 (message):
  Error generating file
  /home/ovs_dl/git/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir//./thundergbm_generated_trainer.cu.o


src/thundergbm/CMakeFiles/thundergbm.dir/build.make:161: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_trainer.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_trainer.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:168: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/all' failed
make[1]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by zeyiwen** [comment]
Looks like your boost library is not properly installed. You may take a look at [this issue](https://github.com/BVLC/caffe/issues/6714), and other similar posts to fix your boost library installation.

**Comment by shijianjian** [comment]
@zeyiwen I have resolved the problem. I think it is about C++ compiler version error. Then the following error appears.
```
CMake Error at thundergbm_generated_tree.cu.o.Release.cmake:219 (message):
  Error generating
  /home/ovs_dl/git/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir//./thundergbm_generated_tree.cu.o


CMake Error at thundergbm_generated_function_builder.cu.o.Release.cmake:219 (message):
  Error generating
  /home/ovs_dl/git/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir/builder/./thundergbm_generated_function_builder.cu.o


CMake Error at thundergbm_generated_objective_function.cu.o.Release.cmake:219 (message):
  Error generating
  /home/ovs_dl/git/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir/objective/./thundergbm_generated_objective_function.cu.o


CMake Error at thundergbm_generated_exact_tree_builder.cu.o.Release.cmake:219 (message):
  Error generating
  /home/ovs_dl/git/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir/builder/./thundergbm_generated_exact_tree_builder.cu.o


CMake Error at thundergbm_generated_shard.cu.o.Release.cmake:219 (message):
  Error generating
  /home/ovs_dl/git/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir/builder/./thundergbm_generated_shard.cu.o


CMake Error at thundergbm_generated_metric.cu.o.Release.cmake:219 (message):
  Error generating
  /home/ovs_dl/git/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir/metric/./thundergbm_generated_metric.cu.o


src/thundergbm/CMakeFiles/thundergbm.dir/build.make:168: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_tree.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_tree.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMake Error at thundergbm_generated_pointwise_metric.cu.o.Release.cmake:219 (message):
  Error generating
  /home/ovs_dl/git/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir/metric/./thundergbm_generated_pointwise_metric.cu.o


CMake Error at thundergbm_generated_row_sampler.cu.o.Release.cmake:219 (message):
  Error generating
  /home/ovs_dl/git/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir//./thundergbm_generated_row_sampler.cu.o

CMake Error at thundergbm_generated_hist_cut.cu.o.Release.cmake:219 (message):
  Error generating
  /home/ovs_dl/git/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir//./thundergbm_generated_hist_cut.cu.o



CMake Error at thundergbm_generated_multiclass_metric.cu.o.Release.cmake:219 (message):
  Error generating
  /home/ovs_dl/git/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir/metric/./thundergbm_generated_multiclass_metric.cu.o


CMake Error at thundergbm_generated_hist_tree_builder.cu.o.Release.cmake:219 (message):
  Error generating
  /home/ovs_dl/git/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir/builder/./thundergbm_generated_hist_tree_builder.cu.o

CMake Error at thundergbm_generated_tree_builder.cu.o.Release.cmake:219 (message):
  Error generating
  /home/ovs_dl/git/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir/builder/./thundergbm_generated_tree_builder.cu.o



src/thundergbm/CMakeFiles/thundergbm.dir/build.make:70: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/builder/thundergbm_generated_function_builder.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/builder/thundergbm_generated_function_builder.cu.o] Error 1
src/thundergbm/CMakeFiles/thundergbm.dir/build.make:133: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/objective/thundergbm_generated_objective_function.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/objective/thundergbm_generated_objective_function.cu.o] Error 1
src/thundergbm/CMakeFiles/thundergbm.dir/build.make:84: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/builder/thundergbm_generated_shard.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/builder/thundergbm_generated_shard.cu.o] Error 1
src/thundergbm/CMakeFiles/thundergbm.dir/build.make:63: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/builder/thundergbm_generated_exact_tree_builder.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/builder/thundergbm_generated_exact_tree_builder.cu.o] Error 1
src/thundergbm/CMakeFiles/thundergbm.dir/build.make:105: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/metric/thundergbm_generated_metric.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/metric/thundergbm_generated_metric.cu.o] Error 1
src/thundergbm/CMakeFiles/thundergbm.dir/build.make:119: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/metric/thundergbm_generated_pointwise_metric.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/metric/thundergbm_generated_pointwise_metric.cu.o] Error 1
src/thundergbm/CMakeFiles/thundergbm.dir/build.make:98: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_hist_cut.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_hist_cut.cu.o] Error 1
src/thundergbm/CMakeFiles/thundergbm.dir/build.make:112: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/metric/thundergbm_generated_multiclass_metric.cu.o' failed
CMake Error at thundergbm_generated_multiclass_obj.cu.o.Release.cmake:219 (message):
  Error generating
  /home/ovs_dl/git/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir/objective/./thundergbm_generated_multiclass_obj.cu.o

make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/metric/thundergbm_generated_multiclass_metric.cu.o] Error 1

src/thundergbm/CMakeFiles/thundergbm.dir/build.make:147: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_row_sampler.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_row_sampler.cu.o] Error 1
CMake Error at thundergbm_generated_predictor.cu.o.Release.cmake:219 (message):
  Error generating
  /home/ovs_dl/git/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir//./thundergbm_generated_predictor.cu.o


src/thundergbm/CMakeFiles/thundergbm.dir/build.make:91: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/builder/thundergbm_generated_tree_builder.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/builder/thundergbm_generated_tree_builder.cu.o] Error 1
src/thundergbm/CMakeFiles/thundergbm.dir/build.make:77: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/builder/thundergbm_generated_hist_tree_builder.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/builder/thundergbm_generated_hist_tree_builder.cu.o] Error 1
CMake Error at thundergbm_generated_sparse_columns.cu.o.Release.cmake:219 (message):
  Error generating
  /home/ovs_dl/git/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir//./thundergbm_generated_sparse_columns.cu.o


src/thundergbm/CMakeFiles/thundergbm.dir/build.make:140: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_predictor.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_predictor.cu.o] Error 1
src/thundergbm/CMakeFiles/thundergbm.dir/build.make:126: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/objective/thundergbm_generated_multiclass_obj.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/objective/thundergbm_generated_multiclass_obj.cu.o] Error 1
src/thundergbm/CMakeFiles/thundergbm.dir/build.make:154: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_sparse_columns.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_sparse_columns.cu.o] Error 1
CMake Error at thundergbm_generated_trainer.cu.o.Release.cmake:219 (message):
  Error generating
  /home/ovs_dl/git/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir//./thundergbm_generated_trainer.cu.o


src/thundergbm/CMakeFiles/thundergbm.dir/build.make:161: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_trainer.cu.o' failed
make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_trainer.cu.o] Error 1
CMakeFiles/Makefile2:168: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/all' failed
make[1]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by zeyiwen** [comment]
You have built the code without errors. They are warnings... It should work.

**Comment by lvpinrui** [comment]
> @zeyiwen嗨，我有提升问题。
> 我使用boost 1.69.0和cmake 3.13.3
> 
> ```
> /usr/local/lib/boost/include/boost/core/noncopyable.hpp(42): error: defaulted default constructor cannot be constexpr because the corresponding implicitly declared default constructor would not be constexpr
> 
> /usr/local/lib/boost/include/boost/mpl/print.hpp(64): warning: integer conversion resulted in a change of sign
> 
> 1 error detected in the compilation of "/tmp/tmpxft_0000135d_00000000-6_trainer.cpp1.ii".
> CMake Error at thundergbm_generated_trainer.cu.o.Release.cmake:279 (message):
>   Error generating file
>   /home/ovs_dl/git/thundergbm/build/src/thundergbm/CMakeFiles/thundergbm.dir//./thundergbm_generated_trainer.cu.o
> 
> 
> src/thundergbm/CMakeFiles/thundergbm.dir/build.make:161: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_trainer.cu.o' failed
> make[2]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/thundergbm_generated_trainer.cu.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> CMakeFiles/Makefile2:168: recipe for target 'src/thundergbm/CMakeFiles/thundergbm.dir/all' failed
> make[1]: *** [src/thundergbm/CMakeFiles/thundergbm.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
> ```
How did you solve it?

**Comment by zeyiwen** [comment]
This problem should be solved now. So, we like to close it.
