### ISSUE TITLE
"File Modification Detected" and errors in Visual Studio 

### ISSUE THREAD

**Issue by AlanSpencer2** [Xtra-Computing/thundergbm#63]
downloaded the branch with cuda 11 support, for win10 and followed the instructions. When building the thundergbm.sln file in Visual Studio, I get a message that says "File Modification Detected". When choosing "Reload All" or any of the other options, the building ends up with a bunch of errors and bugs. Please see the pictures below for more details.

These are the steps I took before getting to the building process:
git clone -b support_cuda11 --single-branch https://github.com/zeyiwen/thundergbm.git
cd thundergbm
git submodule init cub && git submodule update
cd thundergbm
mkdir build
cd build
cmake .. -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE -G "Visual Studio 16 2019"
the last step is to open the file thundergbm.sln and click on "build solution" in the "Build" menu in Visual Studio.

Here is the message window.

![File Modification Detected](https://user-images.githubusercontent.com/94135662/143689925-85b75a59-7b21-4123-b889-6f3f373e7f43.png)

Down below is the errors generated by the building process, in the files xutility, xmemory, atomic and LINK.

![errors thundergbm](https://user-images.githubusercontent.com/94135662/143615583-bb082b6e-8b29-41d4-aa14-866441b4df49.png)

Any idea what might be causing this?

**Comment by QinbinLi** [comment]
Hi @AlanSpencer2 ,

I have installed CUDA 11.5 and visual studio 2019 16.11.8, and followed your instructions to build the project. However, I can successfully build the project without compiling errors. There is a message window that you showed, but it does not affect the compiling of the project. Did you install the necessary components to build C++ projects in Visual Studio (e.g., check "Desktop development with C++" in "Tools->Get Tools and Features" in Visual Studio)?

**Comment by AlanSpencer2** [comment]
Thank you for the reply. I have installed all the default components in "Desktop development with C++" as you can see in the picture below. Do I need to install additional components?

![c++ tools](https://user-images.githubusercontent.com/94135662/146598351-03240df7-fcde-48a3-ac80-2e9458e5979c.png)

**Comment by QinbinLi** [comment]
Hi @AlanSpencer2 ,

The default components should be enough. I also only installed these components. Did you install CUDA before visual studio?  The CUDA toolkit should be installed after visual studio so that the visual studio integration can work. You may try reinstalling CUDA 11.5 and see whether it works.

**Comment by AlanSpencer2** [comment]
Yes, I did install CUDA (11.2) after Visual Studio. And I use other applications that need CUDA without problem. 

You said in your first response that the message should not affect the compiling of the project. But if you look at the error descriptions, you can see that most of them are syntax errors, like parenthesis is missing in the code. If the code misses parenthesis, then it must be fixed. Right? Why would CUDA be the cause of missing parenthesis?

One of the errors says "no suitable constructor exists to convert from el::HitCounter ** to..." and another says "cannot open file ...\thundergbm.lib"...  What do these errors mean?

**Comment by QinbinLi** [comment]
The errors are from files `xutility`, `xmemory`, etc, which are not from the sources files of ThunderGBM. The error "cannot open file ...\thundergbm.lib" means that the compiling is not successful and the library file cannot be generated.

I think the main issue is the incompatibility between your installed versions of CUDA and Visual Studio (and maybe cmake). Here are some references ([ref1](https://stackoverflow.com/questions/67732065/why-does-vs2019-pro-have-compile-errors-with-xutility-xmemory-and-atomic-when), [ref2](https://github.com/actions/virtual-environments/issues/3485)). I suggest you upgrade your CUDA to 11.5, VS to 16.11.8, and cmake to 3.22.1. I can successfully build ThunderGBM with these latest versions.

The screen shot of a successful build is below. For the calling of random forest, please refer to #42 .
![image](https://user-images.githubusercontent.com/25541809/146753024-95c46e43-e887-46be-b863-bb8406654d6c.png)

**Comment by AlanSpencer2** [comment]
One of your references said that removing this string "std=c++14" from the file "CMakeLists" would resolve the issue. I followed that advice which actually removed all the error messages from the building process. After building the project, I then used the command "python setup.py install" in order to install the python wheel inside my python working environment. That process also seemed to go problem free. However, when I try to import the thundergbm library in Jupyter Notebook I get the following error, please see the pictures below:

![import thundergbm error message](https://user-images.githubusercontent.com/94135662/146986160-43255e5e-ee82-4b89-9f84-d60f0ec96fa3.png)

This is a picture of the building process in VS: (Is that successful?)
![building process picture](https://user-images.githubusercontent.com/94135662/146987216-0a260dce-2193-43e7-964c-404bed876753.png)

This is a picture of the command promt when running "python setup.py install": (Is that successful?)
![python setup py install picture](https://user-images.githubusercontent.com/94135662/146987276-4cef1488-1349-4e4b-88ca-4e3816121964.png)

It seems like a successful installation, but why cant I import the thundergbm library?

**Comment by AlanSpencer2** [comment]
I upgraded all the versions as you suggested, CUDA to version 11.5, VS to 16.11.8 and cmake to 3.22.1. The building does not generate any errors anymore, however, the building output is a little different than yours. My output says  "4 succeeded, 0 failed, and 1 skipped". You have "5 succeeded, 0 failed, 0 skipped". 

I still get this error message when trying to import in Python. Did you try to install the python wheel? Does it work for you?

![error message in python](https://user-images.githubusercontent.com/94135662/147487280-e2aecb09-9af3-4a09-9474-fe437549d6ce.png)

**Comment by QinbinLi** [comment]
What is the python version you used? I had the same error if using python 3.9. However, I could successfully import it using python 3.7.8. There may be some issues for python 3.8+ when loading .dll modules. Here are some references [ref1](https://stackoverflow.com/questions/59014318/filenotfounderror-could-not-find-module-libvlc-dll), [ref2](https://stackoverflow.com/questions/59330863/cant-import-dll-module-in-python).
