### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by raijinspecial** [Xtra-Computing/thundergbm#7]
I was able to build thundergbm, but now how do I install it?

**Comment by zeyiwen** [comment]
Do you mean installing ThunderGBM as a system library to allow access from "everywhere"? ThunderGBM doesn't support this currently. We will consider this in our future upgrade if many users have such requirements.

**Comment by zeyiwen** [comment]
ThunderGBM now supports system wide installation using Python. Please check it out from the lastest code and instructions.
