### ISSUE TITLE
Is there a parameter to set "minimum samples per leaf" for Random Forest?

### ISSUE THREAD

**Issue by DonSeger** [Xtra-Computing/thundergbm#70]
I wonder if there is a parameter that corresponds to "minimum samples per leaf" for the Random Forest? If yes, which one? If no, what is the default?

I have seen the page that describes ThunderGBM Parameters, but couldn't find "minimum samples per leaf".
https://github.com/Xtra-Computing/thundergbm/blob/master/docs/parameters.md

**Comment by zeyiwen** [comment]
``min_child_weight`` as described in the [Parameters](https://github.com/Xtra-Computing/thundergbm/blob/master/docs/parameters.md) page.
