### ISSUE TITLE
random seed generator

### ISSUE THREAD

**Issue by RogerBolin** [Xtra-Computing/thundergbm#78]
Hi,

Is there a way to set random seed generator in the thundergbm algorithm in order to achieve reproducibility?

Thanks,
Roger

**Comment by Kurt-Liuhf** [comment]
Hi, setting a random seed using Python API(s) is not supported yet. But if you are using the C++ version, modify this [line](https://github.com/Xtra-Computing/thundergbm/blob/ecb9c0616583005df43c0ed4d331f116a4be6c59/src/thundergbm/row_sampler.cu#L15) to fix the seed.
Thank you.
