### ISSUE TITLE
prediction result

### ISSUE THREAD

**Issue by xingyuezhiji** [Xtra-Computing/thundergbm#8]
为什么`y_predict=clf.predict(x,y)`后输出y_predict结果是none

**Comment by xingyuezhiji** [comment]
代码如下
`x,y = load_svmlight_file("./thundergbm/dataset/test_dataset.txt")
clf = TGBMModel()
clf.fit(x,y)
y_predict=clf.predict(x,y)

print(y_predict)`

**Comment by xingyuezhiji** [comment]
代码如下：
```
x,y = load_svmlight_file("./thundergbm/dataset/test_dataset.txt")
clf = TGBMModel()
clf.fit(x,y)
y_predict=clf.predict(x,y)

print(y_predict)
```

**Comment by zeyiwen** [comment]
Thanks for the feedback! We have fixed the problem. Please pull the latest code, recompile it, and run it again.

**Comment by xingyuezhiji** [comment]
> Thanks for the feedback! We have fixed the problem. Please pull the latest code, recompile it, and run it again.

新的代码预测结果全是0,感觉也不对啊

`print(y_predict,y_predict.sum())`

and the result return `[0. 0. 0. ... 0. 0. 0.] 0.0`

**Comment by zeyiwen** [comment]
Would you share your machine environment (e.g., CUDA version, GPU, OS, etc.)? And dataset if you are not using ```test_dataset.txt```. This will help us reproduce the problem.

Also, please use English, so that the other users and contributors may help fix this issue.

**Comment by xingyuezhiji** [comment]
CUDA Version 9.1.85, OS:ubuntu16.04, GPU1080Ti, and dataset is test_dataset.txt.

**Comment by xingyuezhiji** [comment]
> CUDA Version 9.1.85, OS:ubuntu16.04, GPU1080Ti, and dataset is `test_dataset.txt`.

I have solved it, thanks a lot!

**Comment by zeyiwen** [comment]
Sounds cool. If there is anything needed to be improved, please let us know or even better, contribute to the project :)
